### ISSUE TITLE
Scan completes stating there are major issues while formatting and inserting data into dgraph for Azure

### ISSUE THREAD

**Issue by SY185098** [cloudgraphdev/cli#85]
Thank you for filling out a bug report, we really appreciate any help in improving the CloudGraph CLI and providers!

**Describe the bug**
Scan completes printing the time took to scan each service and at the end, displays there are zero resources found for most services except for first few in the list and at the end displays the message in the below screenshot. Command returns 0 resources even though there are resources present in the subscription

![temp](https://user-images.githubusercontent.com/67426045/169072356-0e21cdd1-c2ed-4026-8f78-4a5ad6787c4c.jpg)

**To Reproduce**
1. Run command 'cg init azure' and provide the required details for authentication
2. Run Command 'cg launch'
3. Run Command 'cg scan'

Please include the `cg-debug.log` file if applicable

**Expected behavior**
Get the number of resources available for each of the services.

**Environment (please complete the following information):**
 - CLI version - @cloudgraph/cli/0.21.4 win32-x64 node-v14.17.6
 - Provider versions - azure@0.61.0
 - Context Trying to setup it up on a Local Machine

**Comment by tyler-dunkel** [comment]
@SY185098 thank you for reporting this! @m-pizarro can you look into this and see whats going on? @SY185098 can you run the command again like so `CG_DEBUG=5 cg scan` so we can get more information on whats wrong.

**Comment by tyler-dunkel** [comment]
Hi @SY185098 we have just released a fix for the issue you are seeing. If you would like to test it, you can do so by running `cg provider add azure@0.61.1-alpha.2` and then running `cg scan`. Please let us know if you encounter any issues or have any questions. Thanks!

**Comment by SY185098** [comment]
Hello @tyler-dunkel and @m-pizarro, still facing the same issue after trying with azure@0.61.1-alpha.2. Also, I see the attached error as well.
![image](https://user-images.githubusercontent.com/67426045/169230462-9fad7a0b-3be3-472a-b729-fca0ce2fa79b.png)
And at the end, 
![image](https://user-images.githubusercontent.com/67426045/169230527-e486ad32-14a5-472e-a8da-ef9443390b89.png)

I tried to run prepend CG_DEBUG=5 before scan command, but it failed with the below error. Should I change any config to resolve this?

![image](https://user-images.githubusercontent.com/67426045/169230753-25c9f821-325b-45af-bdf1-c7245aeb7489.png)

**Comment by m-pizarro** [comment]
Hi @SY185098 , mmh It's weird, I have been testing with the same version and it is working for me. It seems that these errors are due to a issue with the dgraph instance. 

You can try to remove the dgraph container and re-launch it with the following commands:

1. `cg teardown --delete-image`

2. `cg launch`

3. Now rerun the scan to see if this solves the issue: `cg scan` or `CG_DEBUG=5 cg scan`

Please let me know if this solves the problem or if not I will check it again as soon. Thanks!

**Comment by SY185098** [comment]
Hello @m-pizarro, @tyler-dunkel, relaunching cg after scraping dgraph enabled me get the data related to the services.
Although I have the data, I still see the formatting and inserting errors for dgraph while scanning, but nothing is blocking me now!

Thank you so much!!

**Comment by tyler-dunkel** [comment]
Good to hear! It would still be great to try to figure out what is happening on the Dgraph side. @SY185098 would you be open to a short zoom call where we could debug the issue with you?

**Comment by tyler-dunkel** [comment]
@SY185098 I am closing this for now, please let me know if youd like to do a session where we could debug further.
